var arr = ['001A', '002B', '001C', '001B', '002A', '003A', '005E', '006R'];

arr.sort(function (a, b) {
  // Extract the numeric part of the string and convert it to a number
  var numA = parseInt(a.slice(0, 3), 10);
  var numB = parseInt(b.slice(0, 3), 10);

  // Compare the numeric parts
  if (numA < numB) {
    return -1;
  }
  if (numA > numB) {
    return 1;
  }

  // If the numeric parts are equal, compare the letter part
  return a.slice(3).localeCompare(b.slice(3));
});

//////////console.log(arr);
const data = [
  {
    id: 'JDNMzazaIqIPqurPIpoAmB',
    partNumber: 'HDV3457',
    cavity: 34,
    sampleQuantity: 555,
    customer: 'TVS',
    supplier: 'Suzuki',
    reason: '<p>data</p>',
    partName: 'HDV3457',
    model: 'HDV3457',
    productionDate: '2024-01-24',
    typeofRequest: 'Emergency',
    toDepartment: 'ISIR',
    requiredDate: '2024-01-26',
    requestDepartment: 'Testing Dept',
    requestBy: 'planner',
    email: 'testing@gmail.com',
    requestDate: '2024-01-25',
    category: ['Calibration', 'New part'],
    changePointDetails: '<p>data</p>',
    typeOfTest: 'data',
    remarks: '<p>data</p>',
    attachFiles: [
      {
        uid: 'rc-upload-1706153970557-3',
        lastModified: 1705736352260,
        lastModifiedDate: '2024-01-20T07:39:12.260Z',
        name: 'ProdleWireFrames (9).pdf',
        size: 32478,
        type: 'application/pdf',
        percent: 0,
        originFileObj: {
          uid: 'rc-upload-1706153970557-3',
        },
      },
    ],
    overallRemarks: '<p>data</p>',
    status: '',
    receivingStatus: 'receivedAccepeted',
    editDeleteStatus: false,
    buttonStatusEdit: true,
    buttonStatusDelete: true,
    buttonStatusReceiving: true,
    buttonStatusReject: true,
    buttonStatusAllocation: false,
    receivingData: [
      {
        requestDate: '2024-01-25',
        receivingStatus: 'receivedAccepeted',
        requestDepartment: 'Testing Dept',
        requestBy: 'planner',
        email: 'testing@gmail.com',
        receivingPurpose: '',
        receivingRemarks: '',
      },
    ],
    receivingPurpose: '',
    receivingRemarks: '',
    clarification: 'data',
    targetDate: '2024-01-26',
    actualDate: '2024-01-31',
    remarksAllocation: '',
    attachFilesTable: [
      {
        uid: 'rc-upload-1706153970557-11',
        lastModified: 1705736352260,
        lastModifiedDate: '2024-01-20T07:39:12.260Z',
        name: 'ProdleWireFrames (9).pdf',
        size: 32478,
        type: 'application/pdf',
        percent: 0,
        originFileObj: {
          uid: 'rc-upload-1706153970557-11',
        },
      },
    ],
    tableData: [
      {
        instrument: 'Test 1',
        inspector: 'Test 3',
        planTarget: '444',
        actualTarget: '44',
        remarksAllocation: 'ddddd',
        buttonStatus: true,
        id: 'K71ZB3XagrvWHokWc0U1Wd',
      },
    ],
  },
  {
    id: 'cnrnU4Y5r62QKtTBWBhex8',
    partNumber: 'HDV3457',
    cavity: 45,
    sampleQuantity: 566,
    customer: 'TVS',
    supplier: 'Suzuki',
    reason: '<p>dddd</p>',
    partName: 'HDV3457',
    model: 'HDV3457',
    productionDate: '2024-01-25',
    typeofRequest: 'Emergency',
    toDepartment: 'ISIR',
    requiredDate: '2024-01-26',
    requestDepartment: 'Testing Dept',
    requestBy: 'planner',
    email: 'testing@gmail.com',
    requestDate: '2024-01-25',
    category: ['Calibration'],
    changePointDetails: '<p>ddd</p>',
    typeOfTest: 'dddd',
    remarks: '<p>dddd</p>',
    attachFiles: [
      {
        uid: 'rc-upload-1706153970557-7',
        lastModified: 1705558979912,
        lastModifiedDate: '2024-01-18T06:22:59.912Z',
        name: 'ProdleWireFrames (8).pdf',
        size: 29560,
        type: 'application/pdf',
        percent: 0,
        originFileObj: {
          uid: 'rc-upload-1706153970557-7',
        },
      },
    ],
    overallRemarks: '<p>dddddd</p>',
    status: 'rejected',
    receivingStatus: '',
    editDeleteStatus: false,
    buttonStatusEdit: true,
    buttonStatusDelete: true,
    buttonStatusReceiving: true,
    buttonStatusReject: true,
    buttonStatusAllocation: true,
    rejectingData: [
      {
        requestBy: 'planner',
        requestDate: '2024-01-25',
        rejectReason: 'data',
        rejectRemarks: 'data',
      },
    ],
    rejectReason: 'data',
    rejectRemarks: 'data',
  },
  {
    id: 'cmS2iBMSoEeVhsN83v3LD6',
    partNumber: 'HDV3457',
    cavity: 455,
    sampleQuantity: 555,
    customer: 'TVS',
    supplier: 'Suzuki',
    reason: '<p>data</p>',
    partName: 'HDV3457',
    model: 'HDV3457',
    productionDate: '2024-01-24',
    typeofRequest: 'Emergency',
    toDepartment: 'ISIR',
    requiredDate: '2024-01-26',
    requestDepartment: 'Testing Dept',
    requestBy: 'planner',
    email: 'testing@gmail.com',
    requestDate: '2024-01-25',
    category: ['New part', 'Modification'],
    changePointDetails: '<p>data</p>',
    typeOfTest: 'data',
    remarks: '<p>data</p>',
    attachFiles: [
      {
        uid: 'rc-upload-1706153970557-15',
        lastModified: 1705836577705,
        lastModifiedDate: '2024-01-21T11:29:37.705Z',
        name: 'ProdleWireFrames (10).pdf',
        size: 40398,
        type: 'application/pdf',
        percent: 0,
        originFileObj: {
          uid: 'rc-upload-1706153970557-15',
        },
      },
    ],
    overallRemarks: '<p>data</p>',
    status: 'received',
    receivingStatus: 'receivedAccepeted',
    editDeleteStatus: false,
    buttonStatusEdit: true,
    buttonStatusDelete: true,
    buttonStatusReceiving: true,
    buttonStatusReject: true,
    buttonStatusAllocation: false,
    receivingData: [
      {
        requestDate: '2024-01-25',
        receivingStatus: 'receivedAccepeted',
        requestDepartment: 'Testing Dept',
        requestBy: 'planner',
        email: 'testing@gmail.com',
        receivingPurpose: '',
        receivingRemarks: '',
      },
    ],
    receivingPurpose: '',
    receivingRemarks: '',
  },
  {
    id: 'viDJVhGZnOQ1lOM4Zy70cl',
    partNumber: 'HDV3457',
    cavity: 566,
    sampleQuantity: 677,
    customer: 'TVS',
    supplier: 'Suzuki',
    reason: '<p>data</p>',
    partName: 'HDV3457',
    model: 'HDV3457',
    productionDate: '2024-01-25',
    typeofRequest: 'Emergency',
    toDepartment: 'ISIR',
    requiredDate: '2024-01-25',
    requestDepartment: 'Testing Dept',
    requestBy: 'planner',
    email: 'testing@gmail.com',
    requestDate: '2024-01-25',
    category: ['Calibration'],
    changePointDetails: '<p>data</p>',
    typeOfTest: 'data',
    remarks: '<p>data</p>',
    attachFiles: [
      {
        uid: 'rc-upload-1706153970557-19',
        lastModified: 1705736352260,
        lastModifiedDate: '2024-01-20T07:39:12.260Z',
        name: 'ProdleWireFrames (9).pdf',
        size: 32478,
        type: 'application/pdf',
        percent: 0,
        originFileObj: {
          uid: 'rc-upload-1706153970557-19',
        },
      },
    ],
    overallRemarks: '<p>data</p>',
    status: 'request sent',
    receivingStatus: '',
    editDeleteStatus: true,
    buttonStatusEdit: false,
    buttonStatusDelete: false,
    buttonStatusReceiving: false,
    buttonStatusReject: false,
    buttonStatusAllocation: true,
  },
];
