export class CreateDocumentDto {
  doctypeId: string;
  realmName: string;
  documentName: string;
  documentNumbering: string;
  reasonOfCreation: string;
  effectiveDate: string;
  currentVersion: string;
  documentLink: string;
  description: string;
  tags: string[];
  documentState: string;
  retireComment:string;
  referenceDocuments: object[];
  documentVersions: object[];
  additionalReaders: object[];
  reviewers: object[];
  approvers: object[];
  creators: object[];
  file: File;
  locationId: string;
  deleted: boolean;
  entityId: string;
  doctypeName: string;
  systems: string[];
  docsClassification: string;
  issueNumber: string;
  distributionList: string;
  distributionUsers: object[];
  readAccess: string;
  readAccessUsers: object[];
  clause: string[];
  refsData: string[];
  revisionReminder: Boolean;
  approvedDate: Date;
  nextRevisionDate: Date;
  section: Object;
  aceoffixUrl: string;
  revertComment:string;
  createdBy:string;
  organizationId:string;
  locationName:string;
  workflowDetails:any;
}
