/**
 * This file consists of all the authorized access rights given to the specific
 * roles of the users, over the multiple resources.
 */

export const accessRights = {
  admin: {
    ORG_MASTER: ['create', 'read', 'delete', 'update'],
    BUSINESS_CONFIG_MASTER: ['create', 'read', 'delete', 'update'],
    LOCATION_MASTER: ['create', 'read', 'delete', 'update'],
    ENTITY_MASTER: ['create', 'read', 'delete', 'update'],
    USER_MASTER: ['create', 'read', 'delete', 'update'],
    DOCUMENT_TYPE: ['create', 'read', 'delete', 'update'],
    PROCESS_DOCUMENT: ['create', 'read', 'delete', 'update'],
    SYSTEM_MASTER: ['read'],
    AUDIT_TEMPLATE: [],
    AUDIT_ENTRY: [],
    NC: [],
    CONNECTED_APPS: ['read', 'create', 'delete', 'update'],
    KPI_DEFINITION: ['read', 'create', 'delete', 'update'],
    KPI_REPORT_TEMPLATE: ['read', 'create', 'delete', 'update'],
    RISK_CONFIG: ['read'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
  },

  'ORG-ADMIN': {
    ORG_MASTER: ['read', 'update'],
    BUSINESS_CONFIG_MASTER: ['create', 'read', 'update'],
    LOCATION_MASTER: ['create', 'read', 'delete', 'update'],
    ENTITY_MASTER: ['create', 'read', 'delete', 'update'],
    USER_MASTER: ['create', 'read', 'delete', 'update'],
    DOCUMENT_TYPE: ['create', 'read', 'delete', 'update'],
    PROCESS_DOCUMENT: ['create', 'read', 'delete', 'update'],
    SYSTEM_MASTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TEMPLATE: ['create', 'read', 'delete', 'update'],
    AUDIT_ENTRY: ['read', 'update'],
    NC: ['read', 'delete'],
    CONNECTED_APPS: ['read', 'create', 'delete', 'update'],
    KPI_DEFINITION: ['read', 'create', 'delete', 'update'],
    KPI_REPORT_TEMPLATE: ['read', 'create', 'delete', 'update'],
    RISK_CONFIG: ['create', 'read', 'delete', 'update'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TYPE: ['create', 'read', 'delete', 'update'],
    MODEL_MASTER: ['create', 'read', 'delete', 'update'],
  },

  'LOCATION-ADMIN': {
    ORG_MASTER: [],
    BUSINESS_CONFIG_MASTER: [],
    LOCATION_MASTER: ['read', 'update'],
    ENTITY_MASTER: ['create', 'read', 'delete', 'update'],
    USER_MASTER: ['create', 'read', 'delete', 'update'],
    DOCUMENT_TYPE: ['create', 'read', 'delete', 'update'],
    PROCESS_DOCUMENT: ['create', 'read', 'delete', 'update'],
    SYSTEM_MASTER: ['read', 'delete', 'update'],
    AUDIT_TEMPLATE: ['create', 'read', 'delete', 'update'],
    AUDIT_ENTRY: ['read', 'delete'],
    NC: ['read'],
    CONNECTED_APPS: [],
    KPI_DEFINITION: ['read', 'create', 'delete', 'update'],
    KPI_REPORT_TEMPLATE: ['read', 'create', 'delete', 'update'],
    RISK_CONFIG: ['read'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TYPE: ['read'],
    MODEL_MASTER: ['read'],
  },

  MR: {
    ORG_MASTER: [],
    BUSINESS_CONFIG_MASTER: [],
    LOCATION_MASTER: ['read', 'update', 'create'],
    ENTITY_MASTER: ['read', 'create', 'update'],
    USER_MASTER: ['read', 'create', 'update'],
    DOCUMENT_TYPE: ['create', 'read', 'update'],
    PROCESS_DOCUMENT: ['create', 'update'],
    SYSTEM_MASTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TEMPLATE: ['create', 'read', 'delete', 'update'],
    AUDIT_ENTRY: ['read', 'update'],
    NC: ['update'], // only reject / aprove
    CONNECTED_APPS: [],
    KPI_DEFINITION: ['read', 'create', 'update'],
    KPI_REPORT_TEMPLATE: ['read', 'create'],
    RISK_CONFIG: ['create', 'read', 'delete', 'update'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TYPE: ['read'],
    MODEL_MASTER: ['read'],
  },

  // "PLANT-HEAD": {
  //     ORG_MASTER: [],
  //     BUSINESS_CONFIG_MASTER: [],
  //     LOCATION_MASTER: ["read"],
  //     ENTITY_MASTER: ["read"],
  //     USER_MASTER: ["read"],
  //     DOCUMENT_TYPE: ["create", "read", "update"],
  //     PROCESS_DOCUMENT: ["create", "update"]
  // },

  'ENTITY-HEAD': {
    ORG_MASTER: [],
    BUSINESS_CONFIG_MASTER: [],
    LOCATION_MASTER: ['read'],
    ENTITY_MASTER: ['read'],
    USER_MASTER: ['read'],
    DOCUMENT_TYPE: [],
    PROCESS_DOCUMENT: ['create', 'update'],
    SYSTEM_MASTER: ['read'],
    AUDIT_TEMPLATE: ['read'],
    AUDIT_ENTRY: ['read'],
    NC: ['read'],
    CONNECTED_APPS: [],
    KPI_DEFINITION: ['read', 'create'],
    KPI_REPORT_TEMPLATE: ['read', 'create'],
    RISK_CONFIG: ['read'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TYPE: ['read'],
    MODEL_MASTER: ['read'],
  },

  // "SECTION-HEAD": {
  //     ORG_MASTER: [],
  //     BUSINESS_CONFIG_MASTER: [],
  //     LOCATION_MASTER: ["read"],
  //     ENTITY_MASTER: ["read"],
  //     USER_MASTER: ["read"],
  //     DOCUMENT_TYPE: [],
  //     PROCESS_DOCUMENT: ["create", "update"]
  // },

  'GENERAL-USER': {
    ORG_MASTER: [],
    BUSINESS_CONFIG_MASTER: [],
    LOCATION_MASTER: ['read'],
    ENTITY_MASTER: ['read'],
    USER_MASTER: ['read'],
    DOCUMENT_TYPE: [],
    PROCESS_DOCUMENT: ['read'],
    SYSTEM_MASTER: ['read'],
    AUDIT_TEMPLATE: ['read'],
    AUDIT_ENTRY: ['read'],
    NC: ['read'],
    CONNECTED_APPS: [],
    KPI_DEFINITION: ['read'],
    KPI_REPORT_TEMPLATE: ['read'],
    RISK_CONFIG: ['read'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TYPE: ['read'],
    MODEL_MASTER: ['read'],
  },

  AUDITOR: {
    ORG_MASTER: [],
    BUSINESS_CONFIG_MASTER: [],
    LOCATION_MASTER: ['read'],
    ENTITY_MASTER: ['read'],
    USER_MASTER: ['read'],
    DOCUMENT_TYPE: [],
    PROCESS_DOCUMENT: ['read'],
    SYSTEM_MASTER: ['read'],
    AUDIT_TEMPLATE: ['read'],
    AUDIT_ENTRY: ['create', 'read', 'update'],
    NC: ['create', 'read', 'update'],
    CONNECTED_APPS: [],
    KPI_DEFINITION: ['read'],
    KPI_REPORT_TEMPLATE: ['read'],
    RISK_CONFIG: ['read'],
    RISK_REGISTER: ['create', 'read', 'delete', 'update'],
    AUDIT_TYPE: ['read'],
    MODEL_MASTER: ['read'],
  },
};
