
// export const NcAction = {
    
//     NC_ACCEPTED_BY_AUDITEE: "NC_ACCEPTED_BY_AUDITEE",
//     NC_REJECTED_BY_AUDITEE: "NC_REJECTED_BY_AUDITEE",
//     NC_ACCEPTED_BY_MR: "NC_ACCEPTED_BY_MR",
//     NC_REJECTED_BY_MR: "NC_REJECTED_BY_MR",
//     NC_REVIEWED_BY_AUDITOR: "NC_REVIEWED_BY_AUDITOR",
//     NC_CA_TAKEN_BY_AUDITEE: "NC_CA_TAKEN_BY_AUDITEE"

// }

export const NcAction = {
    
    ACCEPTED: "ACCEPTED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    REVIEWED: "REVIEWED",
    REJECTED_AND_CLOSED: "REJECTED & CLOSED",
    VERIFIED:"VERIFIED",
    CLOSED: "CLOSED",
    REMOVED:'REMOVED'

}

export const NcStatus = {
    
    OPEN: "OPEN",
    CLOSED: "CLOSED",
    CANCELLED: "CANCELLED",
    DRAFT: "DRAFT",
    IN_PROGRESS: "IN_PROGRESS",
    ACCEPTED:"ACCEPTED",
    AUDITORREVIEW:"AUDITORREVIEW",
    VERIFIED:"VERIFIED",
    REJECTED: "REJECTED",
    SENTBACK:"SENTBACKTOAUDITEE",
    REMOVED:'REMOVED'

}